{% set name = "autogluon.multimodal" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 96075e9bfce79420fe78a5566a1ba82f9a80598e955f4a4fc490f5561ede70bd

build:
  # noarch: python
  skip: true  # [win or py>=310]
  skip: true  # [linux and cuda_compiler_version not in ("None", "11.2")]
  script: {{ PYTHON }} -m pip install ./multimodal -vv
  number: 6
  script_env:
   - RELEASE=1

requirements:
  build:
    - {{ compiler('cuda') }}                 # [linux and cuda_compiler_version != "None"]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy  >=1.21                          # [build_platform != target_platform]
  host:
    - python # >=3.7,<3.10
    - pip
  run:
    - python # >=3.7,<3.10
    - numpy >=1.21,<1.24  # numpy @ 1.24.1
    - scipy >=1.5.4,<1.10  # scipy @ 1.10.0
    - pandas >1.4.0,<1.6  # pandas @ 1.5.4
    - scikit-learn >=1.0.0,<1.2  # scikit-learn @ 1.2.1
    - pillow >=9.3.0,<=9.4  # pillow @ 9.4.0
    - tqdm >=4.38.0  # tqdm @ 4.46.1
    - boto3
    - requests
    - jsonschema  # jsonschema @ 4.17.3
    - seqeval <=1.2.2  # seqeval @ 1.2.2
    - evaluate <=0.3.0  # evaluate @ 0.3.0
    - accelerate >=0.9,<0.14  # accelerate @ 0.16
    - timm <0.7  # timm @ 0.6.12
    - pytorch >=1.9,<1.14  # pytorch @ 1.13.1
    - torchvision <0.15  # torchvision @ 0.14.1
    - torchtext <0.15  # [not arm64]  torchtext @ 0.14.1
    - fairscale >=0.4.5,<0.4.14  # [not win]  fairscale @ 0.4.13
    - scikit-image >=0.19.1,<0.20  # scikit-image @ 0.19.3
    - smart_open >=5.2.1  # smart_open @ 6.3.0
    - pytorch-lightning >=1.7.4,<1.8  # pytorch-lightning @ 1.9.0
    - text-unidecode <=1.3  # text-unidecode @ 1.3.0
    - torchmetrics >=0.8.0  # torchmetrics @ 0.11.1
    - transformers >=4.23.0  # transformers @ 4.26.0
    - nptyping >=1.4.4,<2  # nptyping @ 2.4.1
    - omegaconf >=2.1.1  # omegaconf @ 2.3.0
    - sentencepiece >=0.1.95  # sentencepiece @ 0.1.97
    - pytorch-metric-learning  # pytorch-metric-learning @ 2.0.0
    - nlpaug >=1.1.10  # nlpaug @ 1.1.11
    - nltk >=3.4.5  # nltk @ 3.8.1
    - openmim  # openmim @ 0.3.5
    - defusedxml >=0.7.1  # defusedxml @ 0.7.1
    - albumentations >=1.1.0  # albumentations @ 1.3.0
    - autogluon.core =={{ version }}
    - autogluon.features =={{ version }}
    - autogluon.common =={{ version }}

test:
  imports:
    - autogluon.multimodal
  commands:
    - python -c "from autogluon.multimodal import __version__ as v; assert v == '{{ version }}', f'{v} != {{ version }}'"
  requires:
    - pip
    - pytorch =*=cuda*  # [linux and cuda_compiler_version != "None"]

about:
  home: https://pypi.org/project/autogluon.multimodal
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
    - Innixma
