{% set name = "autogluon.multimodal" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 96075e9bfce79420fe78a5566a1ba82f9a80598e955f4a4fc490f5561ede70bd

build:
  # noarch: python
  skip: True  # [win or py>=310]
  script: {{ PYTHON }} -m pip install ./multimodal -vv
  number: 4
  script_env:
   - RELEASE=1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy  <1.24,>=1.21                    # [build_platform != target_platform]
  host:
    - python # >=3.7,<3.10
    - pip
  run:
    - python # >=3.7,<3.10
    - numpy <1.24,>=1.21
    - scipy <1.10.0,>=1.5.4
    - pandas !=1.4.0,<1.6,>=1.2.5
    - scikit-learn <1.2,>=1.0.0
    - pillow <=9.4.0,>=9.3.0
    - tqdm >=4.38.0
    - boto3
    - requests
    - jsonschema <=4.8.0
    - seqeval <=1.2.2
    - evaluate <=0.3.0
    - accelerate <0.14,>=0.9
    - timm <0.7.0
    - pytorch <1.13,>=1.9
    - torchvision <0.14.0
    - torchtext <0.14.0  # [not arm64]
    - fairscale <=0.4.6,>=0.4.5  # [not win]
    - scikit-image <0.20.0,>=0.19.1
    - smart_open <5.3.0,>=5.2.1
    - pytorch-lightning <1.8.0,>=1.7.4
    - text-unidecode <=1.3
    - torchmetrics <0.9.0,>=0.8.0
    - transformers <4.24.0,>=4.23.0
    - nptyping <1.5.0,>=1.4.4
    - omegaconf <2.2.0,>=2.1.1
    - sentencepiece <0.2.0,>=0.1.95
    - pytorch-metric-learning # <1.4.0,>=1.3.0
    - nlpaug >=1.1.11  
    - nltk <4.0.0,>=3.4.5
    - openmim # <=0.2.1,>0.1.5
    - defusedxml <=0.7.1,>=0.7.1
    - albumentations <=1.2.0,>=1.1.0
    - autogluon.core =={{ version }}
    - autogluon.features =={{ version }}
    - autogluon.common =={{ version }}

test:
  imports:
    - autogluon.multimodal
  commands:
    - python -c "from autogluon.multimodal import __version__ as v; assert v == '{{ version }}', f'{v} != {{ version }}'"
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon.multimodal
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
    - Innixma
