{% set name = "autogluon.multimodal" %}
{% set version = "1.4.0" %}

# {% set autogluon_proc_type = "cpu" if cuda_compiler_version == "None" else "gpu" %}  # [linux64]
# {% set autogluon_proc_type = "cpu" %}   # [not linux64]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 42e4838bb95328cedb54a9d094072068d8ce1e610a1154f91190b3670011561b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./multimodal -vv
  number: 0 
  script_env:
    - RELEASE=1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy  >=1.25.0,<2.4.0                    # [build_platform != target_platform]
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.13
    - numpy >=1.25.0,<2.4.0
    - scipy >=1.5.4,<1.17
    - pandas >=2.0.0,<2.4.0
    - scikit-learn >=1.4.0,<1.8.0
    - pillow >=10.0.1,<12
    - tqdm >=4.38,<5
    - boto3 >=1.10,<2
    - pytorch >=2.2,<2.8
    - torchvision >=0.16.0,<0.23.0
    - lightning >=2.2,<2.8
    - transformers >=4.38.0,<5
    - sentencepiece >=0.1.91,!=0.1.92
    - accelerate >=0.34.0,<2.0
    - requests >=2.30,<3
    - jsonschema >=4.18,<4.24
    - seqeval >=1.2.2,<1.3.0
    - evaluate >=0.4.0,<0.5.0  
    - timm >=0.9.5,<1.0.7
    - scikit-image >=0.19.1,<0.26.0
    - text-unidecode >=1.3,<1.4
    - torchmetrics >=1.2.0,<1.8
    - omegaconf >=2.1.1,<2.4.0  # setup.py is <2.3.0 but it doesn't work with py311
    - pytorch-metric-learning >=1.3.0,<2.9
    - nlpaug >=1.1.10,<1.2.0
    - nltk >=3.4.5,<3.10
    - openmim >=0.3.7,<0.4.0
    - defusedxml >=0.7.1,<0.7.2
    - jinja2 >=3.0.3,<3.2
    - tensorboard >=2.9,<3
    - pytesseract >=0.3.9,<0.4
    - pdf2image >=1.17.0,<1.19
    - pyopenssl >=23.2.0  # issue https://github.com/conda/conda/issues/13619#issuecomment-2075825121
    - autogluon.core =={{ version }}
    - autogluon.features =={{ version }}
    - autogluon.common =={{ version }}

test:
  imports:
    - autogluon.multimodal
  commands:
    - python -c "from autogluon.multimodal import __version__ as v; from packaging.version import parse; expected = '{{ version }}'; assert parse(v) == parse(expected), f'{v} != {expected}'"
  requires:
    - pip
    - python {{ python_min }}
    # - pytorch =*=cuda*  # [linux and cuda_compiler_version != "None"]

about:
  home: https://pypi.org/project/autogluon.multimodal
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - suzhoum
    - tonyhoo
    - Innixma
    - prateekdesai04
