{% set name = "autogluon.multimodal" %}
{% set version = "1.1.1" %}

# {% set autogluon_proc_type = "cpu" if cuda_compiler_version == "None" else "gpu" %}  # [linux64]
# {% set autogluon_proc_type = "cpu" %}   # [not linux64]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://autogluon.s3.us-west-2.amazonaws.com/tarballs/1.1.1_patch/tarball.tar.gz 
  sha256: e8a23ffc2941e36cf239c472d1fba00a5f660c49a7035c3e6ef1a3a28dd284ea 

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./multimodal -vv
  number: 8
  script_env:
    - RELEASE=1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy  >=1.21,<1.29                    # [build_platform != target_platform]
  host:
    - python >=3.8,<3.13
    - pip
  run:
    - python >=3.8,<3.13
    - numpy >=1.21,<1.29
    - scipy >=1.5.4,<1.15
    - pandas >=2.0.0,<2.3.0
    - scikit-learn >=1.3.0,<1.6
    - pillow >=10.0.1,<11
    - tqdm >=4.38,<5
    - boto3 >=1.10,<2
    - pytorch >=2.1,<2.5
    - pytorch-lightning >=2.1,<2.4
    - lightning >=2.1,<2.4
    - transformers >=4.38.0,<5
    - sentencepiece >=0.1.91,!=0.1.92
    - accelerate >=0.21.0,<0.30
    - requests >=2.21,<3
    - jsonschema >=4.18,<4.24
    - seqeval >=1.2.2,<1.3.0
    - evaluate >=0.4.0,<0.5.0  
    - timm >=0.9.5,<0.10.0
    - scikit-image >=0.19.1,<0.25.0
    - text-unidecode >=1.3,<1.4
    - torchmetrics >=1.2.0,<1.3.0
    - nptyping >=1.4.4,<2.5.0
    - omegaconf >=2.1.1,<2.4.0  # setup.py is <2.3.0 but it doesn't work with py311
    - pytorch-metric-learning >=1.3.0,<2.4
    - nlpaug >=1.1.10,<1.2.0
    - nltk >=3.4.5,<4.0.0
    - openmim >=0.3.7,<0.4.0
    - defusedxml >=0.7.1,<0.7.2
    - jinja2 >=3.0.3,<3.2
    - tensorboard >=2.9,<3
    - pytesseract >=0.3.9,<0.3.11
    - pdf2image >=1.17.0,<1.19
    - autogluon.core =={{ version }}
    - autogluon.features =={{ version }}
    - autogluon.common =={{ version }}

test:
  imports:
    - autogluon.multimodal
  commands:
    - python -c "from autogluon.multimodal import __version__ as v; from packaging.version import parse; expected = '{{ version }}'; assert parse(v) == parse(expected), f'{v} != {expected}'"
  requires:
    - pip
    # - pytorch =*=cuda*  # [linux and cuda_compiler_version != "None"]

about:
  home: https://pypi.org/project/autogluon.multimodal
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - suzhoum
    - tonyhoo
    - giswqs
    - Innixma
    - prateekdesai04
