{% set name = "autogluon.multimodal" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://autogluon.s3.us-west-2.amazonaws.com/tarballs/0.8.3_patch/tarball.tar.gz
  sha256: 1ccc6834b753ad0dc1d96338d8d56ada5b86356a2d34a9e2a29c3e685af277e1 

build:
  noarch: python
  # skip: true  # [py>=311]
  # skip: true  # [linux and cuda_compiler_version not in ("None", "11.2")]
  script: {{ PYTHON }} -m pip install ./multimodal -vv
  number: 3
  script_env:
    - RELEASE=1

requirements:
  build:
    # - {{ compiler('cuda') }}                 # [linux and cuda_compiler_version != "None"]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy  >=1.21,<1.27                    # [build_platform != target_platform]
  host:
    - python >=3.8,<3.11
    - pip
  run:
    - python >=3.8,<3.11
    - numpy >=1.21,<1.27
    - scipy >=1.5.4,<1.12
    - pandas >=1.4.1,<2.2
    - scikit-learn >=1.1,<1.5
    - pillow >=10.2,<11
    - tqdm >=4.38,<5
    - boto3 >=1.10,<2
    - requests >=2.21,<3
    - jsonschema >=4.14,<5.0
    - seqeval >=1.2.2,<1.3.0
    - evaluate >=0.4.0,<0.5.0  # Not matching setup.py definition but conda only has 0.2.2 for now https://github.com/conda-forge/evaluate-feedstock/pull/2
    - accelerate >=0.21.0,<0.22.0
    - timm >=0.9.5,<0.10.0
    - pytorch >=2.0,<2.1
    - torchvision >=0.15.0,<0.16.0
    - scikit-image >=0.19.1,<0.20.0
    - pytorch-lightning >=2.0.0,<2.5
    - text-unidecode >=1.3,<1.4
    - torchmetrics >=1.0.0,<1.1.0
    - transformers >=4.48.0,<5.0.0
    - nptyping >=1.4.4,<2.5.0
    - omegaconf >=2.1.1,<2.3.0
    - sentencepiece >=0.1.91,!=0.1.92
    - protobuf
    - pytorch-metric-learning >=1.3.0,<2.0
    - nlpaug >=1.1.10,<1.2.0
    - nltk >=3.4.5,<4.0.0
    - openmim >=0.3.7,<0.4.0
    - defusedxml >=0.7.1,<0.7.2
    - jinja2 >=3.0.3,<3.2
    - tensorboard >=2.9,<3
    - pytesseract >=0.3.9,<0.3.11
    - autogluon.core =={{ version }}
    - autogluon.features =={{ version }}
    - autogluon.common =={{ version }}

test:
  imports:
    - autogluon.multimodal
  commands:
    - python -c "from autogluon.multimodal import __version__ as v; from packaging.version import parse; expected = '{{ version }}'; assert parse(v) == parse(expected), f'{v} != {expected}'" 
  requires:
    - pip
    # - pytorch =*=cuda*  # [linux and cuda_compiler_version != "None"]

about:
  home: https://pypi.org/project/autogluon.multimodal
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - suzhoum
    - tonyhoo
    - giswqs
    - Innixma
    - prateekdesai04
