{% set autogluon_proc_type = "cpu" %}  # [not linux64]
{% set autogluon_proc_type = "cpu" %}
{% set name = "autogluon.multimodal" %}
{% set version = "1.1.1" %}

# {% set autogluon_proc_type = "cpu" if cuda_compiler_version == "None" else "gpu" %}  # [linux64]
# {% set autogluon_proc_type = "cpu" %}   # [not linux64]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 54eb1b144cbf6980d6fb34d1ccb870f486c3ed9086d9d6e1ff84554e5cab858a

build:
  noarch: python
  # skip: true  # [py>=311]
  # skip: true  # [linux and cuda_compiler_version not in ("None", "11.2")]
  script: {{ PYTHON }} -m pip install ./multimodal -vv
  number: 0
  script_env:
    - RELEASE=1

requirements:
  build:
    # - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy  >=1.21,<1.29                    # [build_platform != target_platform]
  host:
    - python >=3.8,<3.12
    - pip
  run:
    - nvidia-ml ==7.352.0
    - torchvision <0.19.0,>=0.16.0
    - python >=3.8,<3.12
    - numpy <1.29,>=1.21
    - scipy <1.13,>=1.5.4
    - pandas <2.3.0,>=2.0.0
    - scikit-learn <1.4.1,>=1.3.0
    - pillow <11,>=10.0.1
    - tqdm <5,>=4.38
    - boto3 <2,>=1.10
    - pytorch <2.4,>=2.2
    - pytorch-lightning >=2.1,<2.4
    - lightning <2.4,>=2.2
    - transformers <4.41.0,>=4.38.0
    - sentencepiece >=0.1.91,!=0.1.92
    - accelerate <0.22.0,>=0.21.0
    - requests <3,>=2.21
    - jsonschema <4.22,>=4.18
    - seqeval <1.3.0,>=1.2.2
    - evaluate <0.5.0,>=0.4.0
    - timm <0.10.0,>=0.9.5
    - scikit-image <0.21.0,>=0.19.1
    - text-unidecode <1.4,>=1.3
    - torchmetrics <1.3.0,>=1.2.0
    - nptyping <2.5.0,>=1.4.4
    - omegaconf <2.3.0,>=2.1.1  # setup.py is <2.3.0 but it doesn't work with py311
    - pytorch-metric-learning <2.4,>=1.3.0
    - nlpaug <1.2.0,>=1.1.10
    - nltk <4.0.0,>=3.4.5
    - openmim <0.4.0,>=0.3.7
    - defusedxml <0.7.2,>=0.7.1
    - jinja2 <3.2,>=3.0.3
    - tensorboard <3,>=2.9
    - pytesseract <0.3.11,>=0.3.9
    - pdf2image <1.19,>=1.17.0
    - autogluon.core ==1.1.1
    - autogluon.features ==1.1.1
    - autogluon.common ==1.1.1

test:
  imports:
    - autogluon.multimodal
  commands:
    - python -c "from autogluon.multimodal import __version__ as v; assert v == '{{ version }}', f'{v} != {{ version }}'"
  requires:
    - pip
    # - pytorch =*=cuda*  # [linux and cuda_compiler_version != "None"]

about:
  home: https://pypi.org/project/autogluon.multimodal
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - suzhoum
    - tonyhoo
    - giswqs
    - Innixma
